---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    env:
      DEBUG: 1
      HOST: localhost
      PORT: 8000
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      SECRET_KEY: SecretPhrase12345
    steps:
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USER }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: docker-compose run --rm web sh -c "python manage.py test"

      - name: Lint
        run: docker-compose run --rm web sh -c "flake8"